### PR TITLE
change e.s. package to elasticsearch and add maxLogs options

### PR DESCRIPTION
**Pull request by leibale**
add maxLogs options (to delete old logs)

### CODE REVIEW

**Comment by vanthome** [comment]
Solved by 0.2.0

**Comment by leibale** [comment]
i cant see maxLogs in your code

**Comment by vanthome** [comment]
Yea sorry, I need to explain that futher: Philosopically, I think this module should not be responsible for handling this (separation of concerns). I think there should be a job in some job scheduler which deletes stale log indexes. The module is now able to log into indexes depending on a date pattern (daily by default). This makes it easy to identify and remove stale log data. That's what I meant by "solved by 0.2.0".

**Comment by leibale** [comment]
ok, thanks :)

**Pull request closed without merging**
