### PR TITLE
perform writes in bulk

### PR DESCRIPTION
**Pull request by davibe**
Hi, please have a look.

### CODE REVIEW

**Comment by vanthome** [comment]
Hi @davibe many thanks for the PR.
I like the feature and the implementation, the only concern I have is that if ES is unavailable for a long time and you have a lot of messages, you might run out-of-memory.
In my previous implementation the retry functionality prevented that kind of.
I can imagine two solutions:

- we still have a retry mechanism, which discards the accrued batch after some retries
- we introduce something like `maxQueueDepth` which discards everything which is "deeper"

What do you think?

In the meantime, I will merge what you have already and make some minor modifications.

**Comment by davibe** [comment]
I am using this to log many backend instances so I share your concerns. If you start thinking about disaster it all becomes very complicated very quickly :)

With this implementation retry is implicit because if something fails the next `interval` time everything is resent again, nothing is lost. Of course this means keeping stuff in memory and having increasingly bigger bulk requests.

I already thought about `maxQueueDepth` and its pretty easy to do. I will to it as soon as i have the time.

I have seen someone else using rabbitMQ to queue logging messages but i am not sure.. it seems to me the problem is just moved somewhere else, and centralized. RabbitMQ will have to queue and discard messages the same way at some point. Btw, are you using this project at a large scale ?

**Comment by vanthome** [comment]
Yea, generic distributed system fun. I also think RabbitMQ is by far too heavy weight for only this aspect. I think there must be a simple module internal solution.

Sure, retry is implicit now but as you say, it also includes the problem of memory leakage.
The retry I meant would discard the queue after some tries have failed.

The `maxQueueDepth` is straight forward and easy, so let's do this for a new point release.
I will release what we have pretty soon as version `0.3.0`, ok?

**Comment by davibe** [comment]
It's fine by me

**Comment by vanthome** [comment]
I have made some modifications, for example, I no longer do `console.log()` in the bulk writer. Please ckeck my changes, if it's fine for you, I will publish to NPM.

**Pull request merged**
