### PR TITLE
modify schedule leak

### PR DESCRIPTION
**Pull request by econquer**
I have a game service using this module.
My service has a problem about leak a lot of logs on exception.
Please apply this commit and modify this message.
Thank you for winston-elasticsearch!

### CODE REVIEW

**Comment by vanthome** [comment]
I'm sorry, I totally overlooked this! Can you explain your change a bit more?

**Comment by leibale** [comment]
He makes `BulkWriter.prototype.tick` call `BulkWriter.prototype.schedule` even if `BulkWriter.prototype.flush` return an error (buy using `finally` instead of `then`).

**Comment by vanthome** [comment]
I see, it makes sense. It will be part of the next release.

**Comment by vanthome** [comment]
Ok, it's in now. Because finally() is not available in node.js without specifying flags, I implemented the pattern described here:

https://stackoverflow.com/questions/35999072/what-is-the-equivalent-of-bluebird-promise-finally-in-native-es6-promises

Would be good if you could confirm that it fits your purpose.

**Pull request closed without merging**
